import { getCurrentUser } from "@/lib/auth/session";
import { activeMembership } from "@/lib/chat";
import { createThreadReply, listThreadReplies, markThreadRead, publicThreadReply } from "@/lib/chat/thread";
import { errorResponse, json } from "@/lib/http";
export const runtime = "nodejs";
async function auth(roomId: string) { const user = await getCurrentUser(); if (!user) return { error: errorResponse("需要先登录", 401, "UNAUTHENTICATED") }; const member = await activeMembership(roomId, user.id); if (!member) return { error: errorResponse("需要先加入该房间", 403, "FORBIDDEN") }; return { member }; }
export async function GET(request: Request, context: { params: Promise<{ roomId: string; threadId: string }> }) { const { roomId, threadId } = await context.params; const a = await auth(roomId); if (a.error) return a.error; const u = new URL(request.url); const after = Math.max(0, Number(u.searchParams.get("after") ?? 0)); const limit = Number(u.searchParams.get("limit") ?? 50); try { const r = await listThreadReplies(threadId, roomId, Number.isFinite(after) ? after : 0, Number.isFinite(limit) ? limit : 50); return json({ thread: r.thread, replies: r.replies.map(publicThreadReply), nextCursor: r.nextCursor, hasMore: r.hasMore }); } catch (e) { return errorResponse(e instanceof Error ? e.message : "Thread 不存在", 404, "THREAD_NOT_FOUND"); } }
export async function POST(request: Request, context: { params: Promise<{ roomId: string; threadId: string }> }) { const { roomId, threadId } = await context.params; const a = await auth(roomId); if (a.error) return a.error; const body = await request.json().catch(() => ({})); if (typeof body.body !== "string" && typeof body.text !== "string") return errorResponse("正文必填", 400, "VALIDATION_ERROR"); try { const r = await createThreadReply({ roomId, threadId, memberId: a.member.id, body: (body.body ?? body.text) as string, clientId: typeof body.clientId === "string" ? body.clientId : undefined }); return json({ reply: publicThreadReply(r.reply), duplicate: r.duplicate }, { status: r.duplicate ? 200 : 201 }); } catch (e) { return errorResponse(e instanceof Error ? e.message : "无法发送回复", e instanceof Error && e.message === "THREAD_NOT_FOUND" ? 404 : 400, "VALIDATION_ERROR"); } }
export async function PATCH(request: Request, context: { params: Promise<{ roomId: string; threadId: string }> }) { const { roomId, threadId } = await context.params; const a = await auth(roomId); if (a.error) return a.error; const body = await request.json().catch(() => ({})); const seq = Number(body.lastSequence); if (!Number.isFinite(seq)) return errorResponse("lastSequence 不合法", 400, "VALIDATION_ERROR"); await markThreadRead(threadId, a.member.id, seq); return json({ lastSequence: Math.max(0, Math.floor(seq)) }); }
